### ISSUE TITLE
AVP Example

### ISSUE THREAD

**Issue by rodrigo-brito** [pion/ion-avp#126]
Hi Pion Team,

I'm trying to integrate AVP with SFU server.  The example requires an AVP server running and a working client. I do not understand the example very well. I have two questions, maybe you can help me:

 1 - The AVP run in parallel to a working SFU connection or I need to connect the AVP in the mid of the call.
 2 - I started the [SFU server](https://github.com/pion/ion-sfu) and a [JS client](https://github.com/pion/ion-sfu/tree/master/examples/pubsubtest) and the video works well. But when the AVP example requires two params in the client, described above:

`go run examples/save-to-webm/client/main.go $SESSION_ID` 

What is SESSION_ID? Is It the string used in the JS client connection?
```js
const clientLocal = new IonSDK.Client("<SESSION ID>", signalLocal);
```

After the client started, it requires a Track ID. Is it the string specified by SFU server after connection or a random value?
```
[INFO] [163][peer.go][Trickle] => peer ckgzrgi2g00014y85nwhyvfsm trickle
[DEBUG] [68][webrtctransport.go][func1] => Peer ckgzrgi2g00014y85nwhyvfsm got remote track id: 1504e531-02fc-4f37-828d-9facd80b37c1 mediaSSRC: 3726792027 rid : streamID: cp8oDQ2q4qmjrIb5yE58eKTU1YYT2WlncTqj
```
The log above is reported by SFU server, I specified the value `1504e531-02fc-4f37-828d-9facd80b37c1` in AVP client but it does not work. Nothing happens.

**Comment by rodrigo-brito** [comment]
I discovered how it works!

1 - You need a SFU server with both interfaces `gRPC` and `jsonRPC`: 
```bash
go run cmd/signal/allrpc/main.go -c config.toml -jaddr ":7000" -gaddr ":50051"
```
When RPC server is not found, the AVP server stuks in connection step.

2 -  The AVP Client receives SessionID as the first param. It's is the same session ID used to start client connection.
The prompted value called track ID is the `remote track id` used by SFU server, it can be found in SFU server log, as described in the previous comment.

**Comment by tarrencev** [comment]
awesome! hope it is working well for you!

**Comment by djinn09** [comment]
May I asked where did video saved. i follow this but did not find any thing happens after this no video.

**Comment by rodrigo-brito** [comment]
@djinn09 the path is defined in the config file of AVP. The default value of the example is `./out`

**Comment by djinn09** [comment]
Yeah I check that config File.But did not find any out folder made by server or Do i need make manually folder
