### ISSUE TITLE
save-to-webm example key frame problem

### ISSUE THREAD

**Issue by josephGhobadi** [pion/ion-avp#149]
Hi everyone and thank you for writing such amazing package
i use save-to-webm example to save rtp packets on disk but i have a serious problem
sometimes it takes too long for key frame to be generated.
in Chromium browser Version 87.0.4280.66 it takes about 10 seconds. it isn't such a big deal for chromium but for safari 11.1 on ios it takes about 2 minutes until the key-frame recognized and writing to disk initiated! 
`
// Read VP8 header.
		videoKeyframe := (sample.Data[0]&0x1 == 0)
		if videoKeyframe {
			// Keyframe has frame information.
			raw := uint(sample.Data[6]) | uint(sample.Data[7])<<8 | uint(sample.Data[8])<<16 | uint(sample.Data[9])<<24
			width := int(raw & 0x3FFF)
			height := int((raw >> 16) & 0x3FFF)

			if s.videoWriter == nil || s.audioWriter == nil {
				// Initialize WebM saver using received frame size.
				s.InitWriter(width, height)
			}
		}
		if s.videoWriter != nil {
			s.videoTimestamp += sample.Samples
			t := s.videoTimestamp / 90
			if _, err := s.videoWriter.Write(videoKeyframe, int64(t), sample.Data); err != nil {
				fmt.Println(err)
			}
		}`
I also tried to initiate the writing process with some fixed width and height but the output file could not be used 
I'm wondering if there is any workaround or any hacks to address this issue?

**Comment by tarrencev** [comment]
hi @josephGhobadi. sorry for the late reply. we write a PLI to the pub once we start processing the track. that should trigger the pub to send a keyframe. the pub can ignore it though. we should update the service to send PLI on an interval until it gets one
