### ISSUE TITLE
Design question: Record all tracks

### ISSUE THREAD

**Issue by grahamking** [pion/ion-avp#171]
## Summary

I would like to be able to attach an `Element` to all tracks, as they arrive.

## Motivation

The use case is to record audio in an audio conferencing server, where we need all the tracks in a session (everyone's audio on the call). The tracks would be mixed later (with ffmpeg probably). This could apply to video too, where the post-processing might for example display all the recorded videos in a grid.

## Describe alternatives you've considered

I think there's a few ways this could be done:

1. Pass track id "ALL" to WebRTCTransport.Process.
   Create a new element for every existing track, and save the element id to attach to any new tracks.

2. A a new method in server/avp.go, for example `ProcessAll`, which does same as 1.

3. A callback from WebRTCTransport (called from `sub.OnTrack` probably) that tells us there's a new track.
   We would then call `Process` normally, now that we know the track id. The callback would be attached when the session is created, before any tracks are created. This is quite flexible, leaving most of the decision making in the caller.

4. Something else? Maybe there's already a way to do this I'm missing?

## Additional context

Would this be something ion-avp would accept? If yes what design would fit best? I have a very hacky version of 1. working now, but I'd like to do it right before I try to submit it.

Thanks!

**Comment by tarrencev** [comment]
have you looked at the mux element?

**Comment by grahamking** [comment]
I have, but I don't understand it. How would it help here?

**Comment by tarrencev** [comment]
Maybe I am misunderstanding, is your request to default on an element or record all audio tracks in a single webm?

**Comment by grahamking** [comment]
I want to record all audio tracks to a single webm. Second-best (but still very good) would be recording all audio tracks, one track per webm file (because I can merge the webm files offline with ffmpeg).

Is this something ion-avp can do already?

AFAICT my problem is I don't know the track ids, so I can't ask `Process` to record them. Without the track id I can't get WebRTCTransport to attach the `builder` to my element. Hence my idea of making a magic "ALL" track id.

**Comment by grahamking** [comment]
Thanks to @tarrencev 's help I got the track id from the SDP like this:
```
parsed := sdp.SessionDescription{}
if err := parsed.Unmarshal([]byte(desc.SDP)); err == nil {
	for _, md := range parsed.MediaDescriptions {
		if msid, ok := md.Attribute(sdp.AttrKeyMsid); ok {
			split := strings.Split(msid, " ")
			if len(split) != 2 {
				log.Errorf("Invalid msid: %s", msid)
				continue
			}			
			msid := split[0]
			tid := split[1]
                        // call Process here
		}
	}
} else {
	log.Errorf("error parsing sdp media")
}
```

With the track ID, I can control what to record and when, so I don't need this issue any more. Closing.
