### ISSUE TITLE
AVP with ffmpeg

### ISSUE THREAD

**Issue by fenestron** [pion/ion-avp#203]
Hi Pion Team and thanks for this wonderful package!

Please tell me how can I use `ffmpeg` for processing audio and video stream in real time?
This is stated on the [ion page](https://github.com/pion/ion#distributed-real-time-communication-system)
For example, `ffmpeg` accepts a stream and transmits it to the RTMP channel.

Thanks!

**Comment by tarrencev** [comment]
hi @fenestron i would suggest looking at using pion/ion-sdk-go with gstreamer https://github.com/pion/ion-sdk-go/tree/master/example/ion-sfu-gstreamer-receive

**Comment by fenestron** [comment]
This is helpful for my use case. Thank!
